# Generated by Django 4.2.6 on 2023-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_character_selected_voice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='background_image1',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='character',
            name='background_image2',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='character',
            name='background_image3',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='character',
            name='background_image4',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='character',
            name='background_image5',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='character',
            name='selected_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
