# Generated by Django 4.2.6 on 2023-11-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_character_background_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='background_image1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background_image2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background_image3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background_image4',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background_image5',
        ),
    ]
