# Generated by Django 4.2.6 on 2023-11-05 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_prompt', models.TextField(blank=True)),
                ('body_image', models.ImageField(upload_to='images/body/')),
                ('closed_eyes_image', models.ImageField(upload_to='images/eyes/closed/')),
                ('open_eyes_image', models.ImageField(upload_to='images/eyes/open/')),
                ('open_mouth_image', models.ImageField(upload_to='images/mouth/open/')),
                ('half_open_mouth_image', models.ImageField(upload_to='images/mouth/half_open/')),
                ('closed_mouth_image', models.ImageField(upload_to='images/mouth/closed/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/backgrounds/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
