# Generated by Django 4.2.6 on 2023-11-15 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_character_body_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='api_reset_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='api_usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='gpt_prompt',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
