# Generated by Django 4.2.6 on 2023-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_character_api_reset_time_character_api_usage_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='selected_voice_model',
            field=models.CharField(default='kan-bayashi/tsukuyomi_full_band_vits_prosody', max_length=100),
        ),
    ]
