# Generated by Django 4.2.6 on 2023-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_character_background_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='selected_background_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
