# Generated by Django 4.2.6 on 2023-11-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_character_selected_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='new_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
