# Generated by Django 4.2.6 on 2024-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_emailconfirmationtoken_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='selected_voice_model',
            field=models.CharField(default='kan-bayashi/jsut_tacotron2', max_length=100),
        ),
    ]
