# Generated by Django 4.2.6 on 2024-01-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_character_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='closed_mouth_image',
            field=models.ImageField(blank=True, default='images/mouth/closed/mouth_closed.png', upload_to='images/mouth/closed/'),
        ),
    ]
