# Generated by Django 4.2.6 on 2024-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_character_closed_mouth_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='closed_mouth_image',
            field=models.ImageField(blank=True, default='images/mouth/closed/mouth.png', upload_to='images/mouth/close/'),
        ),
    ]
