# Generated by Django 4.2.6 on 2024-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_character_body_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='body_image',
            field=models.ImageField(blank=True, default='images/body.png', upload_to='images/body/'),
        ),
    ]
