# Generated by Django 4.2.6 on 2024-01-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_character_body_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='gpt_prompt1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gpt_prompt2',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gpt_prompt3',
        ),
        migrations.RemoveField(
            model_name='character',
            name='selected_prompt',
        ),
        migrations.AlterField(
            model_name='character',
            name='body_image',
            field=models.ImageField(blank=True, upload_to='body/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='closed_eyes_image',
            field=models.ImageField(blank=True, upload_to='eyes/closed/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='closed_mouth_image',
            field=models.ImageField(blank=True, upload_to='mouth/closed/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='half_open_mouth_image',
            field=models.ImageField(blank=True, upload_to='mouth/half_open/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='open_eyes_image',
            field=models.ImageField(blank=True, upload_to='eyes/open/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='open_mouth_image',
            field=models.ImageField(blank=True, upload_to='mouth/open/'),
        ),
    ]
