# Generated by Django 4.2.6 on 2024-01-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_character_gpt_prompt1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gpt_prompt1',
            field=models.TextField(blank=True, default='デフォルトの値', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='gpt_prompt2',
            field=models.TextField(blank=True, default='デフォルトの値', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='gpt_prompt3',
            field=models.TextField(blank=True, default='デフォルトの値', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='selected_prompt',
            field=models.CharField(choices=[('prompt1', 'Prompt 1'), ('prompt2', 'Prompt 2'), ('prompt3', 'Prompt 3')], default='prompt1', max_length=10),
        ),
    ]
