# Generated by Django 4.2.6 on 2024-02-20 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0027_alter_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='api_max_usage_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='selected_voice_model',
            field=models.CharField(default='kan-bayashi/jsut_full_band_vits_prosody', max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
